apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-app-backend-config
spec:
  healthCheck:
    type: HTTP
    port: 3000
    requestPath: /  # Chắc chắn rằng App của bạn có route app.get('/') 
    checkIntervalSec: 15
    timeoutSec: 5