apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: node-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: node-app
        # ĐÃ SỬA: Bỏ cổng 8085 vì bạn đã dùng Nginx qua 443
        image: nexus.tudaolw.io.vn/docker-hosted/my-node-app:1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: nexus-secret # Tên này phải khớp với cái bạn tạo dưới đây